services:

  postgres:
    image: postgres:16
    container_name: ecommerce_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/initialization:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  airflow-init:
    image: apache/airflow:3.0.6

    container_name: ecommerce_airflow_init

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow

      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__API__AUTH_BACKENDS: >-
        airflow.api.auth.backend.basic_auth,
        airflow.api.auth.backend.session

    user: "${AIRFLOW_UID:-50000}:0"

    command:
      - bash
      - -c
      - |
        airflow db migrate


  airflow-webserver:
    image: apache/airflow:3.0.6

    container_name: ecommerce_airflow_webserver

    restart: unless-stopped

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow

      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__API__AUTH_BACKENDS: >-
        airflow.api.auth.backend.basic_auth,
        airflow.api.auth.backend.session

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

    ports:
      - "${AIRFLOW_PORT}:8080"

    command: api-server


  airflow-scheduler:
    image: apache/airflow:3.0.6

    container_name: ecommerce_airflow_scheduler

    restart: unless-stopped

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow

      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

    command: scheduler


volumes:

  postgres_data: