ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: "{{ env_var('POSTGRES_USER', 'ecommerce_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'ecommerce_password') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'ecommerce') }}"
      schema: analytics
      threads: 4